main: tk.shanebee.redSpawner.RedSpawner
name: RedSpawner
version: 1.1.0[Legacy]
author: ShaneBee
description: Require redstone to power mob spawners
website: https://ShaneBee.tk

commands:
  redspawner:
    description: Commands for RedSpawner
    permission: redspawner.admin
    usage: /redspawner <about/give/reload>
    aliases: rs

permissions:
  redspawner.spawner.*:
    children:
      redspawner.spawner.break: true
      redspawner.spawner.place: true
  redspawner.spawner.break:
    description: Allows a player to break a spawner if SilkTouch is enabled in config
    default: op
  redspawner.spawner.place:
    description: Allows a playre to place a spawner
    default: op
  redspawner.admin:
    description: Allows admins to use redspawner commands
    default: op